/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ContactUs: typeof import('./src/components/ContactUs.vue')['default']
    ContacUs: typeof import('./src/components/ContacUs.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrafficLightTimer: typeof import('./src/components/TrafficLightTimer.vue')['default']
    WhyUs: typeof import('./src/components/WhyUs.vue')['default']
  }
}
